FROM quay.io/fedora/s2i-core:40
WORKDIR /app

RUN dnf -y install "nodejs18" && dnf -y install git nodejs nodejs-nodemon npm jq
COPY ../container_scripts/* .
COPY ../supported_modules.json .

ARG NPM_MODULE
ARG ENABLE_CITGM
RUN ./install_test_module.sh "$NPM_MODULE" "$ENABLE_CITGM"