name: Test Package with CITGM

on:
  workflow_dispatch:
    inputs:
      package:
        description: "Package to test"
        required: true
        type: string
      node-version:
        description: "Node version to test"
        required: true
        type: string
      os:
        description: "Operating System"
        required: false
        type: choice
        default: "ubuntu-latest"
        options:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"
  workflow_call:
    inputs:
      package:
        description: "Package to test"
        required: true
        type: string
      node-version:
        description: "Node version to test"
        required: true
        type: string
        default: "20"
      os:
        description: "Operating System"
        required: false
        type: string
        default: "ubuntu-latest"
jobs:
  core-plugins:
    name: Test with CITGM
    runs-on: ${{inputs.os}}
    permissions:
      contents: read
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Run Tests of ${{inputs.package}} with citgm
        run: |
          npx citgm ${{inputs.package}}
